name: Test
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
jobs:
  test:
    strategy:
      matrix:
        ruby-version: [3.0.x, 2.7.x, 2.6.x, 2.5.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle install
      - run: bundle exec rake
